In [7]:
import json
import sqlalchemy
import pandas as pd
import numpy as np

The next few lines establish a connection to the database. The json credential file uses the following format:
{
    "database": "*****",
     "host": "*****",
     "port": 5432,
     "user": "*****",
     "password": "*****"
}

In [2]:
with open("/home/btphilip/notebooks/SQL_access.json") as f:
    db_conn_dict = json.load(f)

In [3]:
cred_string = 'postgresql://{user}:{password}@{host}:{port}/{database}'.format(**db_conn_dict)

In [4]:
dbeng = sqlalchemy.create_engine(cred_string)

The next few lines read in a csv, selects a subset of the data, stores it as a new variable and prints the variable

In [5]:
df = pd.read_csv('/home/btphilip/snowex/SBBgps20170222A.csv')
temp_df = df[0:99]
#df.head(5)
temp_df

,day.dec,latitude,N/S,longitude,E/W,GPSfix,NSats,HDOP,elevation
1,736382.673333,37.905610,N,107.707903,W,1,7,3.33,3344.1
2,736382.673345,37.905609,N,107.707899,W,1,7,3.33,3343.6
3,736382.673356,37.905608,N,107.707896,W,1,7,3.33,3343.3
4,736382.673368,37.905607,N,107.707892,W,1,7,3.33,3342.7
5,736382.673380,37.905607,N,107.707890,W,1,7,3.33,3342.5
6,736382.673391,37.905607,N,107.707891,W,1,7,3.33,3342.9
7,736382.673403,37.905606,N,107.707893,W,1,7,3.33,3343.6
8,736382.673414,37.905606,N,107.707892,W,1,7,3.34,3343.6
9,736382.673426,37.905606,N,107.707892,W,1,7,3.34,3343.8
10,736382.673438,37.905606,N,107.707893,W,1,7,3.34,3343.9
11,736382.673449,37.905607,N,107.707894,W,1,7,3.34,3344.1
12,736382.673461,37.905608,N,107.707893,W,1,7,3.34,3344.0
13,736382.673472,37.905608,N,107.707893,W,1,7,3.34,3344.1
14,736382.673484,37.905609,N,107.707895,W,1,7,3.34,3344.5
15,736382.673495,37.905610,N,107.707896,W,1,7,3.34,3344.7
16,736382.673507,37.905609,N,107.707896,W,1,7,3.34,3344.7
17,736382.673519,37.905611,N,107.707896,W,1,7,3.34,3344.8
18,736382.673530,37.905611,N,107.707895,W,1,7,3.34,3344.6
19,736382.673542,37.905611,N,107.707896,W,1,7,3.34,3344.6
20,736382.673553,37.905611,N,107.707895,W,1,7,3.35,3344.6
21,736382.673565,37.905610,N,107.707894,W,1,7,3.35,3344.3
22,736382.673576,37.905611,N,107.707894,W,1,7,3.35,3344.4
23,736382.673588,37.905612,N,107.707898,W,1,7,3.35,3345.1
24,736382.673600,37.905611,N,107.707900,W,1,7,3.35,3345.3
25,736382.673611,37.905610,N,107.707903,W,1,7,3.35,3346.0
26,736382.673623,37.905608,N,107.707908,W,1,8,1.64,3346.9
27,736382.673634,37.905607,N,107.707913,W,1,8,1.64,3348.1
28,736382.673646,37.905608,N,107.707914,W,1,8,1.64,3348.4
29,736382.673657,37.905609,N,107.707917,W,1,8,1.64,3348.9
30,736382.673669,37.905609,N,107.707917,W,1,8,1.64,3349.0
...,...,...,...,...,...,...,...,...,...
70,736382.674132,37.905628,N,107.707966,W,1,8,1.63,3356.6
71,736382.674144,37.905629,N,107.707962,W,1,8,1.63,3355.9
72,736382.674155,37.905628,N,107.707960,W,1,8,1.63,3355.6
73,736382.674167,37.905625,N,107.707960,W,1,8,1.63,3355.3
74,736382.674178,37.905628,N,107.707962,W,1,8,1.63,3355.3
75,736382.674190,37.905627,N,107.707963,W,1,8,1.63,3355.2
76,736382.674201,37.905627,N,107.707965,W,1,8,1.63,3355.3
77,736382.674213,37.905628,N,107.707966,W,1,8,1.63,3355.7
78,736382.674225,37.905628,N,107.707966,W,1,8,1.63,3355.7
79,736382.674236,37.905628,N,107.707968,W,1,8,1.63,3355.9
80,736382.674248,37.905628,N,107.707969,W,1,8,1.63,3356.1
81,736382.674259,37.905628,N,107.707969,W,1,8,1.63,3356.0
82,736382.674271,37.905629,N,107.707970,W,1,8,1.63,3355.8
83,736382.674282,37.905631,N,107.707969,W,1,8,1.63,3355.6
84,736382.674294,37.905633,N,107.707972,W,1,8,1.63,3355.2
85,736382.674306,37.905634,N,107.707969,W,1,8,1.63,3355.2
86,736382.674317,37.905635,N,107.707970,W,1,8,1.63,3355.2
87,736382.674329,37.905633,N,107.707970,W,1,8,1.63,3355.2
88,736382.674340,37.905633,N,107.707974,W,1,8,1.63,3355.7
89,736382.674352,37.905631,N,107.707974,W,1,8,1.63,3355.8
90,736382.674363,37.905626,N,107.707976,W,1,8,1.63,3356.3
91,736382.674375,37.905626,N,107.707973,W,1,8,1.62,3356.3
92,736382.674387,37.905626,N,107.707966,W,1,8,1.62,3355.7
93,736382.674398,37.905626,N,107.707964,W,1,8,1.62,3355.8
94,736382.674410,37.905627,N,107.707960,W,1,8,1.62,3355.8
95,736382.674421,37.905627,N,107.707961,W,1,8,1.62,3356.1
96,736382.674433,37.905628,N,107.707961,W,1,8,1.62,3356.0
97,736382.674444,37.905627,N,107.707958,W,1,8,1.62,3356.1
98,736382.674456,37.905623,N,107.707955,W,1,8,1.62,3355.5
99,736382.674468,37.905624,N,107.707954,W,1,8,1.62,3355.7

The following line writes the temp_df variable to a table called "philip_ice_1" on the geohack server (stored here as dbeng). This server is hosted on AWS for the duration of Geohackweek 2017 and was created using the AWS RDS service. I've been using the dBeaver GUI to query and edit the database.

In [6]:
temp_df.to_sql('philip_ice_1', dbeng)